# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rsatsne_cpp <- function(X1, X2, mat12, mat21, nk1, nk2, no_dims, perplexity, theta, verbose, max_iter, distance_precomputed, Y_in, init, stop_lying_iter, mom_switch_iter, momentum, final_momentum, binding_force, coupled_period, uncoupled_period, eta, exaggeration_factor, num_threads) {
    .Call(`_Rsatsne_Rsatsne_cpp`, X1, X2, mat12, mat21, nk1, nk2, no_dims, perplexity, theta, verbose, max_iter, distance_precomputed, Y_in, init, stop_lying_iter, mom_switch_iter, momentum, final_momentum, binding_force, coupled_period, uncoupled_period, eta, exaggeration_factor, num_threads)
}

normalize_input_cpp <- function(input) {
    .Call(`_Rsatsne_normalize_input_cpp`, input)
}

rcpp_hello <- function() {
    .Call(`_Rsatsne_rcpp_hello`)
}

